default:
  #dataDir1: ["./examples/data1/","./examples/data11/","./examples/data12/"]
  #dataDir2: ["./examples/data2/","./examples/data21/","./examples/data22/"]
  #dataDir3: "./examples/data3/"
  betaFileName: "F:/roeder/methylation_transposed2.csv"
  probeAttribut: "probeID"
  dataDir1: ["Z:/EWAS_Parabene_test/all/",
             "Z:/EWAS_Phthalate_test/all/",
             "Z:/EWAS_Biocrates_1LJ/all/",
             "Z:/EWAS_Biocrates_Preg/all/",
	           "Z:/EWAS_DrugMetabolites/all/",
             "Z:/EWAS_MercapturicAcid/all/",
             "Z:/EWAS_Parabene/all/",
             "Z:/EWAS_Parabene/male/",
             "Z:/EWAS_Parabene/female/",
             "Z:/EWAS_Phthalate/all/",
             "Z:/EWAS_Stress/all/",
             "Y:/Home/roeder/daten/Forschungsplanung/EWAS_Zytokine/all/",
             "Z:/EWAS_VitD/all/",
             "Y:/Home/roeder/daten/Forschungsplanung/EWAS_IgE/all/",
	     "Y:/Home/roeder/daten/Forschungsplanung/EWAS_Glyphosate/all/",
	     "Y:/Home/roeder/daten/Forschungsplanung/EWAS_HPLC_Multi/all/",
             "Z:/EWAS_VOC/all/",
             "Z:/EWAS_MVOC/all/",
             "Z:/EWAS_MVOC/male/",
             "Z:/EWAS_MVOC/female/",
             "Z:/EWAS_Q_36SSW/all/",
             "Z:/EWAS_QSoz_36SSW/all/",
             "Z:/EWAS_Treg/all/",
             "Z:/EWAS_Zytokine/all/",
             "Z:/EWAS_SeasonOfBirth/all/",
             "Z:/EWAS_Glyphosate/all/"]

  dataDir2: ["Z:/EWAS_Parabene_test/all/",
             "Z:/EWAS_Phthalate_test/all/",
             "Z:/EWAS_Biocrates_1LJ/all/",
             "Z:/EWAS_Biocrates_Preg/all/",
	     "Z:/EWAS_DrugMetabolites/all/",
             "Z:/EWAS_MercapturicAcid/all/",
             "Z:/EWAS_Parabene/all/",
             "Z:/EWAS_Parabene/male/",
             "Z:/EWAS_Parabene/female/",
             "Z:/EWAS_Phthalate/all/",
             "Z:/EWAS_Stress/all/",
             "Y:/Home/roeder/daten/Forschungsplanung/EWAS_Zytokine/all/",
             "Z:/EWAS_VitD/all/",
             "Y:/Home/roeder/daten/Forschungsplanung/EWAS_IgE/all/",
	     "Y:/Home/roeder/daten/Forschungsplanung/EWAS_Glyphosate/all/",
	     "Y:/Home/roeder/daten/Forschungsplanung/EWAS_HPLC_Multi/all/",
             "Z:/EWAS_VOC/all/",
             "Z:/EWAS_MVOC/all/",
             "Z:/EWAS_MVOC/male/",
             "Z:/EWAS_MVOC/female/",
             "Z:/EWAS_Q_36SSW/all/",
             "Z:/EWAS_QSoz_36SSW/all/",
             "Z:/EWAS_Treg/all/",
             "Z:/EWAS_Zytokine/all/",
             "Z:/EWAS_SeasonOfBirth/all/",
             "Z:/EWAS_Glyphosate/all/"]
  dataDir3:  ["Z:/EWAS_OutcomesLong_test/all/",
             "Z:/EWAS_OutcomesLong/all/",
             "Z:/EWAS_OutcomesLong/male/",
             "Z:/EWAS_OutcomesLong/female/",
             "Y:/Home/roeder/daten/Forschungsplanung/EWAS_Zytokine/all/",
             "Y:/Home/roeder/daten/Forschungsplanung/EWAS_IgE/all/",
             "Z:/EWAS_Stress/all/",
             "Z:/EWAS_MVOC/all/",
             "Z:/EWAS_MVOC/male/",
             "Z:/EWAS_MVOC/female/"]
  workDir: "./inst/extdata/mergedFolder/"
  knownCpGs: "Y:/Home/roeder/daten/Projects/RPackages2/PatternMatchR.UFZ_data/knownCpG.txt"
  knownTraits: "./inst/extdata/knownTraits.txt"
  keyAttributes: ["LINA_ID", "ID_Kind", "KindID", "MutterID", "ID_Mutter"]
  P_VALWarningThreshold: 5e-50
  CpGDistanceThreshold: 100000
  EWAScatalogFileName: "http://ewascatalog.org/static//docs/ewascatalog-results.txt.gz"
  baseURL_EWASDataHub: "https://bigd.big.ac.cn/ewas/datahub/probe/"
  baseURL_MRCEWASCatalog: "http://ewascatalog.org/?query="
  debugMode: TRUE
